
import type { Language } from './types';

export const BARÈME = [
  { lower: 0, upper: 20000, rate: 0 },
  { lower: 20000, upper: 40000, rate: 0.23 },
  { lower: 40000, upper: 80000, rate: 0.27 },
  { lower: 80000, upper: 160000, rate: 0.30 },
  { lower: 160000, upper: 320000, rate: 0.33 },
  { lower: 320000, upper: null, rate: 0.35 },
];

export const CNAS_RATE = 0.09;
export const ABATTEMENT_RATE = 0.4;
export const ABATTEMENT_MIN = 1000;
export const ABATTEMENT_MAX = 1500;
export const EXEMPTION_LIMIT = 30000;

export const I18N: Record<Language, Record<string, string>> = {
  ar: {
    title: "حاسبة ضريبة الدخل IRG الجزائر",
    description: "أداة دقيقة لحساب ضريبة الدخل الإجمالي (IRG) الشهرية وفقًا للتشريع الجزائري.",
    taxableSalary: "الراتب الخاضع للضريبة (DA)",
    grossSalary: "الراتب الإجمالي (DA)",
    calculateCnas: "احسب اقتطاع CNAS (9%)",
    roundingMethod: "طريقة التقريب",
    floor: "قطع (Floor)",
    round: "تقريب (Round)",
    ceil: "رفع (Ceil)",
    calculate: "احسب",
    clear: "مسح",
    results: "النتائج",
    calculationDetails: "تفاصيل الحساب",
    exemptTitle: "معفى من الضريبة",
    exemptMessage: `الراتب الخاضع للضريبة أقل من أو يساوي ${EXEMPTION_LIMIT.toLocaleString('fr-FR')} دج، وبالتالي فهو معفى من IRG.`,
    breakdownTableTitle: "تفصيل الحساب حسب الشرائح",
    bracket: "الشريحة (دج)",
    taxablePart: "الجزء الخاضع",
    rate: "النسبة",
    taxPerBracket: "الضريبة",
    total: "المجموع",
    irgBeforeAbattement: "IRG قبل التخفيض",
    abattementTitle: "التخفيض (Abattement)",
    rawAbattement: `التخفيض الخام (40% من IRG)`,
    monthlyAbattement: "التخفيض الشهري المطبق",
    abattementInfoMin: `تم تطبيق الحد الأدنى (${ABATTEMENT_MIN.toLocaleString('fr-FR')} دج) لأن 40% من IRG أقل من 1000 دج.`,
    abattementInfoMax: `تم تطبيق الحد الأقصى (${ABATTEMENT_MAX.toLocaleString('fr-FR')} دج) لأن 40% من IRG أكبر من 1500 دج.`,
    abattementInfoNone: `تم تطبيق القيمة المحسوبة (40% من IRG) لأنها تقع بين 1000 و 1500 دج.`,
    finalIrgTitle: "IRG النهائي",
    finalIrgRaw: "IRG النهائي (قبل التقريب)",
    finalIrgRounded: "IRG النهائي (بعد التقريب)",
    roundingMethodUsed: "طريقة التقريب المستخدمة",
    netSalary: "الراتب الصافي المقدر",
    legalNote: "آخر تحديث للقواعد: قانون المالية 2025. هذه الأداة للإرشاد فقط.",
    print: "طباعة / PDF",
    exampleSalary: "مثال: 100,725",
    errorInvalidInput: "الرجاء إدخال رقم موجب صالح."
  },
  fr: {
    title: "Calculateur IRG Algérie",
    description: "Outil précis pour calculer l'Impôt sur le Revenu Global (IRG) mensuel selon la législation algérienne.",
    taxableSalary: "Salaire Imposable (DA)",
    grossSalary: "Salaire Brut (DA)",
    calculateCnas: "Calculer la retenue CNAS (9%)",
    roundingMethod: "Méthode d'arrondi",
    floor: "Plancher (Floor)",
    round: "Arrondi (Round)",
    ceil: "Plafond (Ceil)",
    calculate: "Calculer",
    clear: "Effacer",
    results: "Résultats",
    calculationDetails: "Détails du Calcul",
    exemptTitle: "Exonéré d'impôt",
    exemptMessage: `Le salaire imposable est inférieur ou égal à ${EXEMPTION_LIMIT.toLocaleString('fr-FR')} DA, il est donc exonéré d'IRG.`,
    breakdownTableTitle: "Détail du calcul par tranche",
    bracket: "Tranche (DA)",
    taxablePart: "Partie Imposable",
    rate: "Taux",
    taxPerBracket: "Impôt",
    total: "Total",
    irgBeforeAbattement: "IRG avant abattement",
    abattementTitle: "Abattement",
    rawAbattement: "Abattement brut (40% de l'IRG)",
    monthlyAbattement: "Abattement mensuel appliqué",
    abattementInfoMin: `Le minimum (${ABATTEMENT_MIN.toLocaleString('fr-FR')} DA) a été appliqué car 40% de l'IRG est inférieur à 1000 DA.`,
    abattementInfoMax: `Le maximum (${ABATTEMENT_MAX.toLocaleString('fr-FR')} DA) a été appliqué car 40% de l'IRG est supérieur à 1500 DA.`,
    abattementInfoNone: `La valeur calculée (40% de l'IRG) a été appliquée car elle se situe entre 1000 et 1500 DA.`,
    finalIrgTitle: "IRG Final",
    finalIrgRaw: "IRG Final (avant arrondi)",
    finalIrgRounded: "IRG Final (après arrondi)",
    roundingMethodUsed: "Méthode d'arrondi utilisée",
    netSalary: "Salaire Net Estimé",
    legalNote: "Dernière mise à jour des règles : Loi de finances 2025. Cet outil est à titre indicatif.",
    print: "Imprimer / PDF",
    exampleSalary: "Exemple: 100,725",
    errorInvalidInput: "Veuillez entrer un nombre positif valide."
  },
  en: {
    title: "Algeria IRG Tax Calculator",
    description: "An accurate tool to calculate the monthly Gross Income Tax (IRG) according to Algerian legislation.",
    taxableSalary: "Taxable Salary (DA)",
    grossSalary: "Gross Salary (DA)",
    calculateCnas: "Calculate CNAS deduction (9%)",
    roundingMethod: "Rounding Method",
    floor: "Floor",
    round: "Round",
    ceil: "Ceil",
    calculate: "Calculate",
    clear: "Clear",
    results: "Results",
    calculationDetails: "Calculation Details",
    exemptTitle: "Tax Exempt",
    exemptMessage: `The taxable salary is less than or equal to ${EXEMPTION_LIMIT.toLocaleString('fr-FR')} DA, therefore it is exempt from IRG.`,
    breakdownTableTitle: "Calculation Breakdown by Bracket",
    bracket: "Bracket (DA)",
    taxablePart: "Taxable Part",
    rate: "Rate",
    taxPerBracket: "Tax",
    total: "Total",
    irgBeforeAbattement: "IRG before abatement",
    abattementTitle: "Abatement",
    rawAbattement: "Raw Abatement (40% of IRG)",
    monthlyAbattement: "Applied Monthly Abatement",
    abattementInfoMin: `The minimum (${ABATTEMENT_MIN.toLocaleString('fr-FR')} DA) was applied because 40% of IRG is less than 1000 DA.`,
    abattementInfoMax: `The maximum (${ABATTEMENT_MAX.toLocaleString('fr-FR')} DA) was applied because 40% of IRG is greater than 1500 DA.`,
    abattementInfoNone: `The calculated value (40% of IRG) was applied as it is between 1000 and 1500 DA.`,
    finalIrgTitle: "Final IRG",
    finalIrgRaw: "Final IRG (before rounding)",
    finalIrgRounded: "Final IRG (after rounding)",
    roundingMethodUsed: "Rounding method used",
    netSalary: "Estimated Net Salary",
    legalNote: "Rules last updated: Finance Act 2025. This tool is for guidance only.",
    print: "Print / PDF",
    exampleSalary: "Example: 100,725",
    errorInvalidInput: "Please enter a valid positive number."
  }
};
